#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "game/level_geo.h"
#include "game/geo_misc.h"
#include "game/camera.h"
#include "game/moving_texture.h"
#include "game/screen_transition.h"
#include "game/paintings.h"

#include "make_const_nonconst.h"

#include "levels/rr/header.h"

#include "levels/rr/areas/1/2/custom.model.inc.h"
#include "levels/rr/areas/1/2/custom.geo.inc.c"
#include "levels/rr/areas/1/3/custom.model.inc.h"
#include "levels/rr/areas/1/3/custom.geo.inc.c"
#include "levels/rr/areas/1/4/custom.model.inc.h"
#include "levels/rr/areas/1/4/custom.geo.inc.c"
#include "levels/rr/areas/1/5/custom.model.inc.h"
#include "levels/rr/areas/1/5/custom.geo.inc.c"
#include "levels/rr/areas/1/6/custom.model.inc.h"
#include "levels/rr/areas/1/6/custom.geo.inc.c"
#include "levels/rr/areas/1/7/custom.model.inc.h"
#include "levels/rr/areas/1/7/custom.geo.inc.c"
#include "levels/rr/areas/1/8/custom.model.inc.h"
#include "levels/rr/areas/1/8/custom.geo.inc.c"
#include "levels/rr/areas/1/9/custom.model.inc.h"
#include "levels/rr/areas/1/9/custom.geo.inc.c"
#include "levels/rr/areas/1/10/custom.model.inc.h"
#include "levels/rr/areas/1/10/custom.geo.inc.c"
#include "levels/rr/areas/1/11/custom.model.inc.h"
#include "levels/rr/areas/1/11/custom.geo.inc.c"
#include "levels/rr/areas/1/12/geo.inc.c"
#include "levels/rr/areas/1/13/geo.inc.c"
#include "levels/rr/areas/1/14/custom.model.inc.h"
#include "levels/rr/areas/1/14/custom.geo.inc.c"
#include "levels/rr/areas/1/15/custom.model.inc.h"
#include "levels/rr/areas/1/15/custom.geo.inc.c"
#include "levels/rr/areas/1/16/custom.model.inc.h"
#include "levels/rr/areas/1/16/custom.geo.inc.c"
#include "levels/rr/areas/1/17/geo.inc.c"
#include "levels/rr/areas/1/18/custom.model.inc.h"
#include "levels/rr/areas/1/18/custom.geo.inc.c"
#include "levels/rr/areas/1/19/geo.inc.c"
#include "levels/rr/areas/1/20/geo.inc.c"
#include "levels/rr/areas/1/21/geo.inc.c"
#include "levels/rr/flying_carpet/geo.inc.c"
#include "levels/rr/swinging_platform/custom.model.inc.h"
#include "levels/rr/swinging_platform/custom.geo.inc.c"
#include "levels/rr/rotating_bridge_platform/custom.model.inc.h"
#include "levels/rr/rotating_bridge_platform/custom.geo.inc.c"
#include "levels/rr/cruiser_wing/geo.inc.c"
#include "levels/rr/octagonal_platform/custom.model.inc.h"
#include "levels/rr/octagonal_platform/custom.geo.inc.c"
#include "levels/rr/sliding_platform/custom.model.inc.h"
#include "levels/rr/sliding_platform/custom.geo.inc.c"
#include "levels/rr/pyramid_platform/geo.inc.c" // unused
#include "levels/rr/elevator_platform/custom.model.inc.h"
#include "levels/rr/elevator_platform/custom.geo.inc.c"
#include "levels/rr/seesaw_platform/custom.model.inc.h"
#include "levels/rr/seesaw_platform/custom.geo.inc.c"
#include "levels/rr/donut_block/custom.model.inc.h"
#include "levels/rr/donut_block/custom.geo.inc.c"
#include "levels/rr/l_platform/custom.model.inc.h" // also unused
#include "levels/rr/l_platform/custom.geo.inc.c" // also unused
#include "levels/rr/tricky_triangles_1/custom.model.inc.h"
#include "levels/rr/tricky_triangles_1/custom.geo.inc.c"
#include "levels/rr/tricky_triangles_2/custom.model.inc.h"
#include "levels/rr/tricky_triangles_2/custom.geo.inc.c"
#include "levels/rr/tricky_triangles_3/geo.inc.c"
#include "levels/rr/tricky_triangles_4/custom.model.inc.h"
#include "levels/rr/tricky_triangles_4/custom.geo.inc.c"
#include "levels/rr/tricky_triangles_5/geo.inc.c"
#include "levels/rr/areas/1/geo.inc.c"
