#ifndef transparent_star_transparent_star_model_HEADER_H
#define transparent_star_transparent_star_model_HEADER_H
#include "types.h"
extern Vtx VB_transparent_star_geo_0x302c4a0[];
extern Light_t Light_transparent_star_geo_0x302c490;
extern Ambient_t Light_transparent_star_geo_0x302c488;
extern Gfx DL_transparent_star_geo_0x302c620[];
extern Gfx DL_transparent_star_geo_0x302c560[];
#endif