COURSE_ACTS(COURSE_BOB, _(" 1 BOB-OMB ISLANDS"),	_("BIG BOB-OMB'S SKY FORT"),	_("TOP OF THE SUNKEN SHIP"),	_("IN THE SIDE OF THE MOUNTAIN"),	_("FIND THE 8 RED COINS"),	_("DEEP DIVE IN THE CAGE"),	_("SMASH THE CHAIN CHOMP'S ROCKS"))

COURSE_ACTS(COURSE_WF, _(" 2 SKY LAND RESORT"),	_("THE NEW WHOMP KING"),	_("CLIMB THE WINDMILL"),	_("THE FLYING STEPPING STONES"),	_("FINDING THE PURPLE SWITCH"),	_("RED COINS OF THE SKY"),	_("BEHIND THE UNDERWATER GATE"))

COURSE_ACTS(COURSE_JRB, _(" 3 PIRANHA PLANT POND"),	_("CLIMB THE RUINS"),	_("THE FLOODED CAVE"),	_("8 RED COINS OF THE POND"),	_("SHOOT TO THE TOWER TOP"),	_("UNDERWATER METAL DASH"),	_("THE OWL'S DINNER TIME"))

COURSE_ACTS(COURSE_CCM, _(" 4 CHUCKYA HARBOR"),	_("CLIMB TO THE HIGHEST POLE"),	_("SWIM INTO THE FLOODED CAGE"),	_("THE UNDERWATER MAZE"),	_("BREAK INTO THE BUILDING"),	_("THE CHUCKYA'S RED COINS"),	_("THE OTHER ENTRANCE"))

COURSE_ACTS(COURSE_BBH, _(" 5 GLOOMY GARDEN"),	_("BIG BOO'S TOWER"),	_("TOP OF THE RISKY WALKWAY"),	_("THE SECRET TUNNEL"),	_("THE LONE TREE"),	_("HAUNTED RIDE FOR RED COINS"),	_("CALM THE ANGRY EYE"))

COURSE_ACTS(COURSE_HMC, _(" 6 COLORFUL CORAL CAVERNS"),	_("DEEP DIVE THROUGH THE CORAL"),	_("BOAT RIDE AMONG THE ROCKS"),	_("BREAK THROUGH THE FLOOR"),	_("PRECISION SWIMMING"),	_("RED COINS OF THE DEEP"),	_("THE 'X' MARKS THE SPOT"))

COURSE_ACTS(COURSE_LLL, _(" 7 KOOPA CANYON"),	_("THE ANGRY SUN'S PYRAMID CLIMB"),	_("SANDY RACE WITH KOOPA THE QUICK"),	_("ANCIENT TREASURE INSIDE THE PYRAMID"),	_("8 ROCKY RED COINS"),	_("GLIDE FROM THE QUICKSAND TORNADO"),	_("SINKY SPIRAL CAVE"))

COURSE_ACTS(COURSE_SSL, _(" 8 LARGE LEAF FOREST"),	_("A BIG BUG PROBLEM"),	_("SHINING DOWN FROM THE TREE TOPS"),	_("QUICK LILY PAD HOP"),	_("THE BEE'S TREASURE"),	_("VINE-CLIMBING FOR 8 RED COINS"),	_("THE MISSING STAR"))

COURSE_ACTS(COURSE_DDD, _(" 9 MAD MUSICAL MESS"),	_("THE PIANO-PLAYING THWOMPS"),	_("MOUTH OF THE GIANT FLUTE"),	_("TRICKY TAMBOURINE TRICK"),	_("CRAZY NOTE CLIMB"),	_("THE 8 MUSICAL RED COINS"),	_("TO STRUM THE GUITAR..."))

COURSE_ACTS(COURSE_SL, _("10 MELTING SNOW PEAKS"),	_("CHILLY LOOKOUT FIGHT"),	_("THE SNOWMAN'S DEN"),	_("ICY SHELL RIDE"),	_("THE LOST PENGUIN"),	_("CLIFF JUMPING FOR RED COINS"),	_("GLIDE TO THE HIDDEN LEDGE"))

COURSE_ACTS(COURSE_WDW, _("11 COLOSSAL CANDY CLUTTER"),	_("TUXIE RACE DOWN THE SLIDE"),	_("TOP OF THE TOY TOWER"),	_("DOOR-KNOCKING"),	_("MOVING TARGET"),	_("POLE-JUMPING"),	_("PLAYFUL RED COINS"))

COURSE_ACTS(COURSE_TTM, _("12 CLOUDRAIL STATION"),	_("SWINGING THROUGH THE CLOUDS"),	_("PLATFORM RIDE TO THE CAGE"),	_("FLUFFY CASTLE CLIMB"),	_("THE FROZEN CLOUD"),	_("THE GIANT THWOMP'S TREASURE"),	_("AIRBORNE RED COINS"))

COURSE_ACTS(COURSE_THI, _("13 FATAL FLAME FALLS"),	_("DEEP IN THE FLAMING CAVERNS"),	_("CROSS THE LAVA LAKE"),	_("METAL MARIO MELTDOWN"),	_("CLIMB THE CENTRAL LOOKOUT"),	_("BURNING RED COINS"),	_("RISKY RIDE INTO THE VOLCANO"))

COURSE_ACTS(COURSE_TTC, _("14 BOB-OMB BATTLE FACTORY"),	_("TOP OF THE FACTORY"),	_("WALL KICK UP THE TOWER"),	_("CAREFUL CRANE CLAMBER"),	_("SWIRLY SUCTION WALL"),	_("THE RUSTY RED COINS"),	_("THE ENGINE LEAK"))

COURSE_ACTS(COURSE_RR, _("15 STARLIGHT RUNWAY"),	_("FOLLOW THE GLITTERING PATH"),	_("CLIMB THROUGH THE MACHINERY"),	_("SHUTDOWN THE HANDROID"),	_("AIM THE TURRET"),	_("RED COINS IN THE CRATER"),	_("IN THE CAGE"))

SECRET_STAR(15, _("   BOWSER'S SLIPPERY SWAMP"))
SECRET_STAR(16, _("   RETRO REMIX CASTLE"))
SECRET_STAR(17, _("   BOWSER'S RAINBOW RUMBLE"))
SECRET_STAR(18, _("   MUSHROOM MOUNTAIN TOWN"))
SECRET_STAR(19, _("   CREEPY CAP CAVE"))
SECRET_STAR(20, _("   WINDY WING CAP WELL"))
SECRET_STAR(21, _("   PUZZLE OF THE VANISH CAP"))
SECRET_STAR(22, _("   HIDDEN PALACE FINALE"))
SECRET_STAR(23, _("   SANDY SLIDE SECRET"))
SECRET_STAR(24, _(""))
CASTLE_SECRET_STARS(_("   SECRET STARS"))
EXTRA_TEXT(0,_("ONE OF THE SECRET STARS!"))
EXTRA_TEXT(1,_("TEST"))
EXTRA_TEXT(2,_(""))
EXTRA_TEXT(3,_(""))
EXTRA_TEXT(4,_(""))
EXTRA_TEXT(5,_(""))
EXTRA_TEXT(6,_(""))
