#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "game/level_geo.h"
#include "game/geo_misc.h"
#include "game/camera.h"
#include "game/moving_texture.h"
#include "game/screen_transition.h"
#include "game/paintings.h"

#include "make_const_nonconst.h"

#include "levels/bbh/header.h"

#include "levels/bbh/staircase_step/custom.model.inc.h"
#include "levels/bbh/staircase_step/custom.geo.inc.c"
#include "levels/bbh/tilting_trap_platform/custom.model.inc.h"
#include "levels/bbh/tilting_trap_platform/custom.geo.inc.c"
#include "levels/bbh/tumbling_platform_far/geo.inc.c"
#include "levels/bbh/tumbling_platform_near/custom.model.inc.h"
#include "levels/bbh/tumbling_platform_near/custom.geo.inc.c"
#include "levels/bbh/moving_bookshelf/custom.model.inc.h"
#include "levels/bbh/moving_bookshelf/custom.geo.inc.c"
#include "levels/bbh/mesh_elevator/custom.model.inc.h"
#include "levels/bbh/mesh_elevator/custom.geo.inc.c"
#include "levels/bbh/merry_go_round/custom.model.inc.h"
#include "levels/bbh/merry_go_round/custom.geo.inc.c"
#include "levels/bbh/coffin/geo.inc.c"
#include "levels/bbh/areas/1/geo.inc.c"
