const GeoLayout haunted_cage_geo[]= {
GEO_CULLING_RADIUS(300),
GEO_OPEN_NODE(),
GEO_SHADOW(0,150,100),
GEO_OPEN_NODE(),
GEO_DISPLAY_LIST(0,0),
GEO_DISPLAY_LIST(0,0),
GEO_DISPLAY_LIST(0,0),
GEO_CLOSE_NODE(),
GEO_CLOSE_NODE(),
GEO_END(),
};
